packages:
  - apps/*
  - packages/*
  - packages/ui-components/*
  - '!packages/park/**'
  - '!**/test/**'
  - '!**/.vercel/**'
  - '!**/cache-directory/**'
  - '!**/dist/**'
  - '!**/build/**'
  - '!**/.turbo/**'

catalog:
  '@astrojs/check': ^0.9.4
  '@astrojs/mdx': ^4.3.4
  '@astrojs/preact': ^4.1.0
  '@astrojs/react': ^4.3.0
  '@astrojs/rss': ^4.0.12
  '@astrojs/sitemap': ^3.5.1
  '@astrojs/vercel': ^8.2.7
  '@astrojs/vue': ^5.1.0
  '@awesome.me/webawesome': 3.0.0-beta.4
  '@eslint/css':  "^0.11.0"
  '@eslint/compat': ^1.3.2
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.35.0
  '@eslint/json': ^0.13.2
  '@eslint/markdown': ^7.1.0
  '@headlessui/react': ^2.2.7
  '@headlessui/vue': ^1.7.23
  '@heroicons/react': ^2.2.0
  '@heroicons/vue': ^2.2.0
  '@iarna/toml': ^2.2.5
  '@iconify-json/mdi': ^1.2.3
  '@open-wc/testing': ^4.0.0
  '@preact/preset-vite': ^2.10.2
  '@preact/signals': ^2.3.1
  '@prettier/plugin-oxc': ^0.0.4
  '@sentry/astro': ^8.55.0
  '@sentry/browser': ^8.55.0
  '@sentry/cli': ^2.52.0
  '@sentry/vite-plugin': ^3.6.1
  '@tailwindcss/cli': ^4.1.13
  '@tailwindcss/postcss': ^4.1.13
  '@tailwindcss/typography': ^0.5.16
  '@tailwindcss/vite': ^4.1.13
  '@types/node': ~22.18.1
  '@types/react': ^19.1.12
  '@types/react-dom': ^19.1.9
  '@typescript-eslint/parser': ^8.42.0
  '@vitejs/plugin-react': ^5.0.0
  '@vitejs/plugin-vue': ^6.0.1
  '@webcomponents/template-shadowroot': ^0.2.1
  '@yusifaliyevpro/countries': ^2.2.2
  add: 2.0.6
  astro: 5.13.5
  astro-eslint-parser: ^1.2.2
  astro-icon: ^1.1.5
  clsx: ^2.1.1
  daisyui: ^5.1.8
  date-fns: ^4.1.0
  dotenv: ^17.2.2
  eslint: ^9.35.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-astro: ^1.3.1
  eslint-plugin-barrel-files: ^3.0.1
  eslint-plugin-lit: ^2.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-turbo: ^2.5.6
  eslint-plugin-vue: ^10.4.0
  eslint-plugin-wc: ^3.0.1
  globals: ^16.3.0
  gsap: ^3.13.0
  jest: ^30.1.3
  lorem-ipsum: ^2.0.8
  luxon: ^3.7.1
  preact: ^10.27.1
  prettier: ^3.6.2
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-tailwindcss: ^0.6.14
  prettier-plugin-toml: ^2.0.6
  prettier-plugin-vue: ^1.1.6
  react: ^19.1.1
  react-dom: ^19.1.1
  rollup-plugin-visualizer: ^6.0.3
  sharp: ^0.34.3
  tailwind-merge: ^3.3.1
  tailwindcss: ~4.1.13
  theme-change: ^2.5.0
  tsup: ^8.5.0
  typescript: ^5.9.2
  typescript-eslint: ^8.42.0
  vite: ^6.3.5
  vue: ^3.5.21
  vue-eslint-parser: ^10.2.0
  zod-validation-error: ^3.5.3

catalogs:
  starlight:
    '@astrojs/starlight': ^0.35.2
  svelte5:
    '@astrojs/svelte': ^7.1.0
    '@sveltejs/vite-plugin-svelte': ^6.1.4
    eslint-plugin-svelte: ^3.12.2
    prettier-plugin-svelte: ^3.4.0
    svelte: ^5.38.7
    svelte-check: ^4.3.1
    svelte-eslint-parser: ^1.3.1

cleanupUnusedCatalogs: true
