packages:
  - apps/*
  - packages/*
  - packages/ui-components/*
  - '!packages/park/**'
  - '!**/test/**'
  - '!**/.vercel/**'
  - '!**/cache-directory/**'
  - '!**/dist/**'
  - '!**/build/**'
  - '!**/.turbo/**'

catalog:
  '@astrojs/check': ^0.9.5
  '@astrojs/mdx': ^4.3.9
  '@astrojs/preact': ^4.1.2
  '@astrojs/react': ^4.4.1
  '@astrojs/rss': ^4.0.13
  '@astrojs/sitemap': ^3.6.0
  '@astrojs/vercel': ^9.0.0
  '@astrojs/vue': ^5.1.2
  '@eslint/compat': ^1.4.1
  '@eslint/css': ^0.14.1
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.39.1
  '@eslint/json': ^0.14.0
  '@eslint/markdown': ^7.5.1
  '@headlessui/react': ^2.2.9
  '@headlessui/vue': ^1.7.23
  '@heroicons/react': ^2.2.0
  '@heroicons/vue': ^2.2.0
  '@iarna/toml': ^2.2.5
  '@iconify-json/mdi': ^1.2.3
  '@open-wc/testing': ^4.0.0
  '@preact/preset-vite': ^2.10.2
  '@preact/signals': ^2.3.2
  '@prettier/plugin-oxc': ^0.0.4
  '@sentry/astro': ^8.55.0
  '@sentry/browser': ^9.46.0
  '@sentry/cli': ^2.57.0
  '@sentry/vite-plugin': ^3.6.1
  '@tailwindcss/cli': ^4.1.16
  '@tailwindcss/postcss': ^4.1.16
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': 4.1.16
  '@types/node': ~22.19.0
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  '@typescript-eslint/parser': ^8.46.3
  '@vitejs/plugin-react': ^5.1.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/coverage-istanbul': ^4.0.3
  '@vitest/ui': ^4.0.3
  '@webcomponents/template-shadowroot': ^0.2.1
  '@yusifaliyevpro/countries': ^2.2.2
  add: 2.0.6
  astro: 5.15.3
  astro-eslint-parser: ^1.2.2
  astro-icon: ^1.1.5
  clsx: 2.1.1
  daisyui: ^5.4.3
  date-fns: ^4.1.0
  dotenv: ^17.2.3
  eslint: ^9.39.1
  eslint-config-prettier: ^10.1.8
  eslint-plugin-astro: ^1.4.0
  eslint-plugin-barrel-files: ^3.0.1
  eslint-plugin-lit: ^2.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-turbo: ^2.6.0
  eslint-plugin-vue: ^10.5.1
  eslint-plugin-wc: ^3.0.2
  glob: ^11.0.3
  globals: ^16.5.0
  gsap: ^3.13.0
  jest: ^30.2.0
  jsdom: ^27.1.0
  lorem-ipsum: ^2.0.8
  nyc: ^17.1.0
  preact: ^10.27.2
  prettier: ^3.6.2
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-tailwindcss: ^0.7.1
  prettier-plugin-toml: ^2.0.6
  prettier-plugin-vue: ^1.1.6
  react: 19.2.0
  react-dom: 19.2.0
  rollup-plugin-visualizer: ^6.0.5
  sharp: ^0.34.4
  sitemap: ^8.0.2
  tailwind-merge: 3.3.1
  tailwindcss: ~4.1.16
  theme-change: ^2.5.0
  tsup: ^8.5.0
  typescript: ^5.9.3
  typescript-eslint: ^8.46.3
  vite: ^7.1.12
  vitest: ^3.2.4
  vue: ^3.5.22
  vue-eslint-parser: ^10.2.0
  zod-validation-error: ^3.5.3

catalogs:
  starlight:
    '@astrojs/starlight': ^0.36.2
  svelte5:
    '@astrojs/svelte': ^7.2.1
    '@sveltejs/vite-plugin-svelte': ^6.2.1
    eslint-plugin-svelte: ^3.13.0
    prettier-plugin-svelte: ^3.4.0
    svelte: ^5.43.3
    svelte-check: ^4.3.3
    svelte-eslint-parser: ^1.4.0

cleanupUnusedCatalogs: true
