packages:
  - apps/*
  - packages/*
  - packages/ui-components/*
  - '!packages/park/**'
  - '!**/test/**'
  - '!**/.vercel/**'
  - '!**/cache-directory/**'
  - '!**/dist/**'
  - '!**/build/**'
  - '!**/.turbo/**'

catalog:
  '@astrojs/check': ^0.9.6
  '@astrojs/mdx': ^4.3.12
  '@astrojs/preact': ^4.1.3
  '@astrojs/react': ^4.4.2
  '@astrojs/rss': ^4.0.14
  '@astrojs/sitemap': ^3.6.0
  '@astrojs/vercel': ^9.0.2
  '@astrojs/vue': ^5.1.3
  '@eslint/compat': ^2.0.0
  '@eslint/css': ^0.14.1
  '@eslint/eslintrc': ^3.3.3
  '@eslint/js': ^9.39.1
  '@eslint/json': ^0.14.0
  '@eslint/markdown': ^7.5.1
  '@headlessui/react': ^2.2.9
  '@headlessui/vue': ^1.7.23
  '@heroicons/react': ^2.2.0
  '@heroicons/vue': ^2.2.0
  '@iarna/toml': ^2.2.5
  '@iconify-json/mdi': ^1.2.3
  '@open-wc/testing': ^4.0.0
  '@preact/preset-vite': ^2.10.2
  '@preact/signals': ^2.5.1
  '@prettier/plugin-oxc': ^0.1.3
  '@sentry/astro': ^8.55.0
  '@sentry/browser': ^9.46.0
  '@sentry/cli': ^2.57.0
  '@sentry/vite-plugin': ^3.6.1
  '@tailwindcss/cli': ^4.1.17
  '@tailwindcss/postcss': ^4.1.17
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': 4.1.17
  '@types/node': ~24.10.1
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@typescript-eslint/parser': ^8.49.0
  '@vitejs/plugin-react': ^5.1.1
  '@vitejs/plugin-vue': ^6.0.2
  '@vitest/coverage-istanbul': ^4.0.8
  '@vitest/ui': ^4.0.10
  '@webcomponents/template-shadowroot': ^0.2.1
  '@yusifaliyevpro/countries': ^2.2.2
  add: 2.0.6
  astro: 5.16.5
  astro-eslint-parser: ^1.2.2
  astro-icon: ^1.1.5
  clsx: 2.1.1
  daisyui: ^5.5.11
  date-fns: ^4.1.0
  dotenv: ^17.2.3
  eslint: ^9.39.1
  eslint-config-prettier: ^10.1.8
  eslint-plugin-astro: ^1.5.0
  eslint-plugin-barrel-files: ^3.0.1
  eslint-plugin-lit: ^2.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-turbo: ^2.6.3
  eslint-plugin-vue: ^10.6.2
  eslint-plugin-wc: ^3.0.2
  glob: ^13.0.0
  globals: ^16.5.0
  gsap: ^3.14.1
  jest: ^30.2.0
  jsdom: ^27.3.0
  lorem-ipsum: ^2.0.8
  nyc: ^17.1.0
  preact: ^10.28.0
  prettier: ^3.7.4
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-tailwindcss: ^0.7.2
  prettier-plugin-toml: ^2.0.6
  prettier-plugin-vue: ^1.1.6
  react: 19.2.1
  react-dom: 19.2.1
  sharp: ^0.34.5
  sitemap: ^9.0.0
  tailwind-merge: 3.4.0
  tailwindcss: ~4.1.17
  theme-change: ^2.5.0
  tsup: ^8.5.1
  typescript: ^5.9.3
  typescript-eslint: ^8.49.0
  vite: ^7.2.7
  vitest: ^3.2.4
  vue: ^3.5.25
  vue-eslint-parser: ^10.2.0
  zod-validation-error: ^3.5.3

catalogs:
  starlight:
    '@astrojs/starlight': ^0.37.1
  svelte5:
    '@astrojs/svelte': ^7.2.3
    '@sveltejs/vite-plugin-svelte': ^6.2.1
    eslint-plugin-svelte: ^3.13.1
    prettier-plugin-svelte: ^3.4.0
    svelte: ^5.45.8
    svelte-check: ^4.3.4
    svelte-eslint-parser: ^1.4.1

cleanupUnusedCatalogs: true
