packages:
  - 'apps/astrodemo'
  - 'apps/mike-blog'
  - 'apps/multi-app'
  - 'apps/pico-astro-theme'
  - 'packages/**'
    # exclude packages that are inside test directories
  - '!**/test/**'
    # Below excludes are only for Turbo because it doesn't respect gitignore like pnpm does
  - '!**/.vercel/**'
