packages:
  - apps/*
  - apps-to-off-ramp/apps-svelte/*
  - packages/*
  - packages/ui-components/*
  - "!**/test/**"
  - "!**/.vercel/**"
  - "!**/cache-directory/**"
catalogs:
  svelte5:
    "@astrojs/svelte": ^7.0.13
    "@sveltejs/adapter-auto": ^3.3.1
    svelte: ^5.28.2
    svelte-check: ^4.1.7
    svelte-preprocess: ^6.0.3
    prettier-plugin-svelte: ^3.3.2
    vite: ^6.2.6
catalog:
  "@astrojs/check": ^0.9.4
  "@astrojs/markdoc": ^0.14.2
  "@astrojs/mdx": ^4.2.6
  "@astrojs/node": ^9.2.1
  "@astrojs/preact": ^4.0.11
  "@astrojs/react": ^4.2.7
  "@astrojs/rss": ^4.0.11
  "@astrojs/sitemap": ^3.3.1
  "@astrojs/solid-js": ^5.0.10
  "@astrojs/starlight": ^0.34.2
  "@astrojs/starlight-markdoc": ^0.4.0
  "@astrojs/vercel": ^8.1.4
  "@astrojs/vue": ^5.0.13
  "@custom-elements-manifest/analyzer": ^0.10.4
  "@eslint/compat": ^1.2.4
  "@eslint/eslintrc": ^3.3.1
  "@eslint/js": ^9.26.0
  "@eslint/json": ^0.12.0
  "@eslint/markdown": ^6.4.0
  "@headlessui/react": ^2.2.2
  "@headlessui/vue": ^1.7.23
  "@heroicons/react": ^2.2.0
  "@heroicons/vue": ^2.2.0
  "@iconify-json/mdi": ^1.2.3
  "@next/eslint-plugin-next": ^15.3.1
  "@open-wc/testing": ^4.0.0
  "@playform/compress": ^0.1.9
  "@preact/signals": ^2.0.4
  "@sentry/astro": ^8.55.0
  "@sentry/browser": ^8.55.0
  "@sentry/cli": ^2.43.1
  "@sentry/vite-plugin": ^3.3.1
  "@sveltejs/vite-plugin-svelte": ^5.0.3
  "@tailwindcss/cli": ^4.1.5
  "@tailwindcss/postcss": ^4.1.3
  "@tailwindcss/typography": ^0.5.16
  "@tailwindcss/vite": ^4.1.5
  "@types/canvas-confetti": ^1.9.0
  "@types/node": ^22.15.3
  "@types/react": ^19.1.2
  "@types/react-dom": ^19.1.3
  "@typescript-eslint/utils": ^8.31.1
  "@vanilla-extract/vite-plugin": ^4.0.16
  "@vitejs/plugin-vue": ^5.2.3
  "@web/test-runner": ^0.19.0
  "@webcomponents/template-shadowroot": ^0.2.1
  add: ^2.0.6
  astro: ^5.7.10
  astro-embed: ^0.9.0
  astro-eslint-parser: ^1.2.2
  astro-icon: ^1.1.5
  astro-og-canvas: ^0.7.0
  autoprefixer: ^10.4.21
  canvas-confetti: ^1.9.3
  clsx: ^2.1.1
  cssnano: ^7.0.6
  daisyui: ^5.0.35
  date-fns: ^4.1.0
  dotenv: ^16.5.0
  eslint: ^9.26.0
  eslint-config-prettier: ^10.1.2
  eslint-plugin-astro: ^1.3.1
  eslint-plugin-barrel-files: ^3.0.1
  eslint-plugin-lit: ^2.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-solid: ^0.14.5
  eslint-plugin-svelte: ^3.5.1
  eslint-plugin-turbo: ^2.5.2
  eslint-plugin-vue: ^10.1.0
  eslint-plugin-wc: ^3.0.1
  globals: ^16.0.0
  jest: ^29.7.0
  lit: ^3.3.0
  lorem-ipsum: ^2.0.8
  luxon: ^3.6.1
  open-props: ^1.7.15
  postcss: ^8.5.2
  postcss-custom-media: ^11.0.5
  postcss-html: ^1.7.0
  postcss-import: ^16.1.0
  postcss-jit-props: ^1.0.16
  postcss-nesting: ^13.0.1
  postcss-pow: ^1.0.1
  preact: ^10.26.4
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-tailwindcss: ^0.6.11
  prettier-plugin-vue: ^1.1.6
  react: ^19.0.0
  react-dom: ^19.1.0
  rollup-plugin-visualizer: ^5.14.0
  sharp: ^0.34.1
  solid-js: ^1.9.6
  svelte-eslint-parser: ^1.1.3
  tailwind-merge: ^3.2.0
  tailwindcss: ^4.1.5
  tsup: ^8.4.0
  turbo: ^2.5.2
  typescript: ^5.8.3
  typescript-eslint: ^8.31.1
  vite: ^6.3.4
  vitest: ^2.1.6
  vue: ^3.5.13
  vue-eslint-parser: ^10.1.3
  zod: ^3.24.2
  zod-validation-error: ^3.4.0
