packages:
  - apps/*
  - apps-to-off-ramp/apps-svelte/*
  - apps/astro-themes/*
  - packages/*
  - packages/ui-components/*
  - '!**/test/**'
  - '!**/.vercel/**'
  - '!**/cache-directory/**'

catalog:
  '@astrojs/check': ^0.9.4
  '@astrojs/preact': ^4.0.9
  '@astrojs/react': ^4.2.4
  '@preact/signals': ^2.0.3
  '@astrojs/mdx': ^4.2.4
  '@astrojs/rss': ^4.0.11
  '@astrojs/sitemap': ^3.2.1
  '@astrojs/tailwind': ^6.0.0
  '@astrojs/vercel': ^8.1.3
  '@astrojs/vue': ^5.0.4
  '@custom-elements-manifest/analyzer': ^0.10.3
  '@eslint/compat': ^1.2.4
  '@iconify-json/mdi': ^1.2.3
  '@open-wc/testing': ^4.0.0
  '@tailwindcss/postcss': ^4.1.3
  '@types/react': ^19.1.2
  '@types/react-dom': ^19.1.2
  '@vanilla-extract/vite-plugin': ^4.0.16
  '@web/test-runner': ^0.19.0
  '@webcomponents/template-shadowroot': ^0.2.1
  '@tailwindcss/vite': ^4.1.4
  '@types/node': ^22.14.1
  astro: ^5.7.2
  add: ^2.0.6
  astro-icon: ^1.1.5
  autoprefixer: ^10.4.21
  cssnano: ^7.0.6
  dotenv: ^16.4.7
  eslint: ^9.24.0
  jest: ^29.7.0
  lit: ^3.3.0
  open-props: ^1.7.15
  postcss: ^8.5.2
  postcss-custom-media: ^11.0.5
  postcss-html: ^1.7.0
  postcss-import: ^16.1.0
  postcss-jit-props: ^1.0.16
  postcss-nesting: ^13.0.1
  postcss-pow: ^1.0.1
  preact: ^10.26.4
  prettier-plugin-astro: ^0.14.1
  react: ^19.0.0
  react-dom: ^19.1.0
  sharp: ^0.34.1
  tailwindcss: ^4.1.4
  '@tailwindcss/typography': ^0.5.16
  typescript: ^5.8.3
  vite: ^6.3.0
  vitest: ^2.1.6
  vue: ^3.5.13
  zod: ^3.24.2

catalogs:
  svelte5:
    '@astrojs/svelte': ^7.0.10
    '@sveltejs/adapter-auto': ^3.3.1
    svelte: ^5.27.0
    svelte-check: ^4.1.6
    svelte-preprocess: ^6.0.3
    prettier-plugin-svelte: ^3.3.2
    vite: ^6.2.6
