packages:
  - apps/*
  - apps-astro-themes/*
  - "!apps-svelte/*"
  - "!apps/hackernews/*"
  - packages/*
  - packages/ui-components/*
  - "!**/test/**"
  - "!**/.vercel/**"
  - "!**/cache-directory/**"

catalog:
  "@astrojs/check": ^0.9.4
  "@astrojs/preact": ^4.0.5
  "@preact/signals": ^2.0.0
  "@astrojs/react": ^4.2.1
  "@astrojs/mdx": ^4.1.0
  "@astrojs/rss": ^4.0.11
  "@astrojs/sitemap": ^3.2.1
  "@astrojs/svelte": ^7.0.5
  "@astrojs/tailwind": ^6.0.0
  "@astrojs/vercel": ^8.0.7
  "@astrojs/vue": ^5.0.4
  "@custom-elements-manifest/analyzer": ^0.10.3
  "@eslint/compat": ^1.2.4
  "@iconify-json/mdi": ^1.2.3
  "@open-wc/testing": ^4.0.0
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4
  "@vanilla-extract/vite-plugin": ^4.0.16
  "@web/test-runner": ^0.19.0
  "@webcomponents/template-shadowroot": ^0.2.1
  "@types/node": ^22.13.5
  add: ^2.0.6
  astro-icon: ^1.1.5
  autoprefixer: ^10.4.20
  cssnano: ^7.0.6
  dotenv: ^16.4.7
  eslint: ^9.21.0
  jest: ^29.7.0
  lit: ^3.2.1
  open-props: ^1.7.13
  postcss: ^8.5.2
  postcss-custom-media: ^11.0.5
  postcss-html: ^1.7.0
  postcss-import: ^16.1.0
  postcss-jit-props: ^1.0.16
  postcss-nesting: ^13.0.1
  postcss-pow: ^1.0.1
  preact: ^10.26.3
  prettier-plugin-astro: ^0.14.1
  react: ^19.0.0
  react-dom: ^19.0.0
  sharp: ^0.33.5
  tailwindcss: ^4.0.6
  typescript: ^5.7.3
  vite: ^5.4.11
  vitest: ^2.1.6
  vue: ^3.5.13
  zod: ^3.24.2

catalogs:
  astro4:
    "@astrojs/check": ^0.9.4
    "@astrojs/starlight": ^0.29.0
    "@astrojs/vercel": ^7.8.2
    "@astrojs/lit": ^4.3.0
    astro: ^4.16.14
    sharp: ^0.33.5
  svelte5:
    "@astrojs/svelte": ^7.0.3
    "@sveltejs/adapter-auto": ^3.3.1
    svelte: ^5.20.5
    svelte-check: ^4.1.3
    svelte-preprocess: ^6.0.3
    prettier-plugin-svelte: ^3.3.2
    vite: ^6.0.3
