packages:
  - apps/*
  - packages/*
  - packages/ui-components/*
  - '!**/test/**'
  - '!**/.vercel/**'
  - '!**/cache-directory/**'
catalogs:
  svelte5:
    '@astrojs/svelte': ^7.1.0
    '@sveltejs/adapter-auto': ^6.0.1
    svelte: ^5.33.4
    svelte-check: ^4.2.1
    svelte-preprocess: ^6.0.3
    prettier-plugin-svelte: ^3.4.0
    vite: ^6.3.5
catalog:
  '@astrojs/check': ^0.9.4
  '@astrojs/markdoc': ^0.15.0
  '@astrojs/mdx': ^4.3.0
  '@astrojs/node': ^9.2.2
  '@astrojs/preact': ^4.1.0
  '@astrojs/react': ^4.3.0
  '@astrojs/rss': ^4.0.11
  '@astrojs/sitemap': ^3.4.0
  '@astrojs/solid-js': ^5.1.0
  '@astrojs/starlight': ^0.34.3
  '@astrojs/starlight-markdoc': ^0.4.0
  '@astrojs/vercel': ^8.1.4
  '@astrojs/vue': ^5.1.0
  '@custom-elements-manifest/analyzer': ^0.10.4
  '@eslint/compat': ^1.2.9
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.27.0
  '@eslint/json': ^0.12.0
  '@eslint/markdown': ^6.4.0
  '@headlessui/react': ^2.2.4
  '@headlessui/vue': ^1.7.23
  '@heroicons/react': ^2.2.0
  '@heroicons/vue': ^2.2.0
  '@iconify-json/mdi': ^1.2.3
  '@next/eslint-plugin-next': ^15.3.2
  '@open-wc/testing': ^4.0.0
  '@playform/compress': ^0.1.9
  '@preact/signals': ^2.1.1
  '@sentry/astro': ^8.55.0
  '@sentry/browser': ^8.55.0
  '@sentry/cli': ^2.43.1
  '@sentry/vite-plugin': ^3.3.1
  '@sveltejs/vite-plugin-svelte': ^5.0.3
  '@tailwindcss/cli': ^4.1.7
  '@tailwindcss/postcss': ^4.1.7
  '@tailwindcss/typography': ^0.5.16
  '@tailwindcss/vite': ^4.1.7
  '@types/canvas-confetti': ^1.9.0
  '@types/node': ^22.15.23
  '@types/react': ^19.1.6
  '@types/react-dom': ^19.1.5
  '@vitejs/plugin-vue': ^5.2.4
  '@webcomponents/template-shadowroot': ^0.2.1
  add: ^2.0.6
  astro: ^5.8.0
  astro-embed: ^0.9.0
  astro-eslint-parser: ^1.2.2
  astro-icon: ^1.1.5
  astro-og-canvas: ^0.7.0
  autoprefixer: ^10.4.21
  canvas-confetti: ^1.9.3
  clsx: ^2.1.1
  cssnano: ^7.0.7
  daisyui: ^5.0.40
  date-fns: ^4.1.0
  dotenv: ^16.5.0
  eslint: ^9.27.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-astro: ^1.3.1
  eslint-plugin-barrel-files: ^3.0.1
  eslint-plugin-lit: ^2.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-solid: ^0.14.5
  eslint-plugin-svelte: ^3.6.0
  eslint-plugin-turbo: ^2.5.3
  eslint-plugin-vue: ^10.1.0
  eslint-plugin-wc: ^3.0.1
  globals: ^16.2.0
  jest: ^29.7.0
  lit: ^3.3.0
  lorem-ipsum: ^2.0.8
  luxon: ^3.6.1
  open-props: ^1.7.15
  postcss: ^8.5.2
  postcss-custom-media: ^11.0.5
  postcss-html: ^1.7.0
  postcss-import: ^16.1.0
  postcss-jit-props: ^1.0.16
  postcss-nesting: ^13.0.1
  postcss-pow: ^1.0.1
  preact: ^10.26.7
  prettier: ^3.5.3
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-tailwindcss: ^0.6.11
  prettier-plugin-toml: ^2.0.5
  prettier-plugin-vue: ^1.1.6
  react: ^19.0.0
  react-dom: ^19.1.0
  rollup-plugin-visualizer: ^6.0.0
  sharp: ^0.34.2
  solid-js: ^1.9.6
  svelte-eslint-parser: ^1.1.3
  tailwind-merge: ^3.3.0
  tailwindcss: ^4.1.7
  theme-change: ^2.5.0
  tsup: ^8.5.0
  turbo: ^2.5.3
  typescript: ^5.8.3
  typescript-eslint: ^8.33.0
  vite: ^6.3.5
  vitest: ^3.1.4
  vue: ^3.5.15
  vue-eslint-parser: ^10.1.3
  zod: ^3.25.32
  zod-validation-error: ^3.4.1
