packages:
  - apps/*
  - packages/**
  - "!packages/ui/**"
  - "!packages/solid/**"
  - "!**/test/**"
  - "!**/.vercel/**"
catalog:
  "@astrojs/check": ^0.9.4
  "@astrojs/lit": ^4.3.0
  "@astrojs/mdx": ^3.1.8
  "@astrojs/preact": ^3.5.3
  "@astrojs/react": ^3.6.2
  "@astrojs/rss": ^4.0.9
  "@astrojs/sitemap": ^3.2.1
  "@astrojs/starlight": ^0.28.3
  "@astrojs/svelte": ^5.7.2
  "@astrojs/tailwind": ^5.1.2
  "@astrojs/vercel": ^7.8.2
  "@astrojs/vue": ^4.5.2
  "@custom-elements-manifest/analyzer": ^0.10.3
  "@eslint/js": ^9.13.0
  "@eslint/json": ^0.5.0
  "@eslint/markdown": ^6.2.1
  "@iconify-json/mdi": ^1.2.1
  "@open-wc/testing": ^4.0.0
  "@shoelace-style/shoelace": ^ 2.18.0
  "@types/eslint__js": ^8.42.3
  "@types/eslint-config-prettier": ^6.11.3
  "@types/react": ^18.3.11
  "@types/react-dom": ^18.3.1
  "@vanilla-extract/vite-plugin": ^4.0.16
  "@web/test-runner": ^0.19.0
  "@webcomponents/template-shadowroot": ^0.2.1
  add: ^2.0.6
  astro-eslint-parser: ^1.0.3
  astro-icon: ^1.1.1
  autoprefixer: ^10.4.20
  cssnano: ^7.0.6
  eslint: ^9.13.0
  eslint-config-prettier: ^9.1.0
  eslint-plugin-astro: ^1.3.0
  eslint-plugin-lit: ^1.15.0
  eslint-plugin-react: ^7.37.2
  eslint-plugin-regexp: ^2.6.0
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-solid: ^0.14.3
  eslint-plugin-svelte: ^2.46.0
  eslint-plugin-wc: ^2.2.0
  globals: ^15.11.0
  jest: ^29.7.0
  lit: ^3.2.1
  open-props: ^1.7.7
  postcss: ^8.4.47
  postcss-custom-media: ^11.0.3
  postcss-html: ^1.7.0
  postcss-import: ^16.1.0
  postcss-jit-props: ^1.0.14
  postcss-nesting: ^13.0.0
  postcss-pow: ^1.0.1
  preact: ^10.24.3
  prettier: ^3.3.3
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-svelte: ^3.2.7
  react: ^18.3.1
  react-dom: ^18.3.1
  sharp: ^0.33.5
  stylelint: ^16.10.0
  svelte: ^4.2.19
  svelte-check: ^4.0.5
  svelte-preprocess: ^6.0.3
  tailwindcss: ^3.4.3
  turbo: ^2.2.3
  typescript: ^5.6.3
  typescript-eslint: ^8.11.0
  vite: ^5.4.9
  vitest: ^2.1.3
  vue: ^3.5.12
  zod: ^3.23.8
