packages:
  - "apps/astrodemo"
  - "apps/mike-blog"
  - "apps/multi-app"
  - "apps/starlight"
  - "apps/beta5"
  # 'apps/pico-astro-theme'
  - "packages/**"
  - "!packages/ui/**"
  - "!packages/solid/**"
    # exclude packages that are inside test directories
  - "!**/test/**"
    # Below excludes are only for Turbo because it doesn't respect gitignore like pnpm does
  - "!**/.vercel/**"
