packages:
  - docs/*
  - apps/*
  - "!apps/pico-astro-theme/**"
  - "!apps/starlight/**"
  - "!apps/shop/**"
  - packages/**
  - "!packages/ui/**"
  - "!packages/solid/**"
  - "!**/test/**"
  - "!**/.vercel/**"
  - "!**/cache-directory/**"
catalog:
  "@astrojs/check": ^0.9.4
  "@astrojs/lit": ^4.3.0
  "@astrojs/preact": ^3.5.3
  "@astrojs/react": ^3.6.2
  "@astrojs/rss": ^4.0.9
  "@astrojs/sitemap": ^3.2.1
  "@astrojs/starlight": ^0.28.3
  "@astrojs/svelte": ^5.7.2
  "@astrojs/tailwind": ^5.1.2
  "@astrojs/vercel": ^7.8.2
  "@astrojs/vue": ^4.5.2
  "@custom-elements-manifest/analyzer": ^0.10.3
  "@iconify-json/mdi": ^1.2.1
  "@open-wc/testing": ^4.0.0
  "@shoelace-style/shoelace": ^2.17.1
  "@types/react": ^18.3.12
  "@types/react-dom": ^18.3.1
  "@vanilla-extract/vite-plugin": ^4.0.16
  "@web/test-runner": ^0.19.0
  "@webcomponents/template-shadowroot": ^0.2.1
  add: ^2.0.6
  astro: 5.0.0-beta.8
  astro-icon: ^1.1.2
  autoprefixer: ^10.4.20
  cssnano: ^7.0.6
  eslint: ^9.14.0
  jest: ^29.7.0
  lit: ^3.2.1
  open-props: ^1.7.7
  postcss: ^8.4.49
  postcss-custom-media: ^11.0.5
  postcss-html: ^1.7.0
  postcss-import: ^16.1.0
  postcss-jit-props: ^1.0.14
  postcss-nesting: ^13.0.1
  postcss-pow: ^1.0.1
  preact: ^10.24.3
  prettier: ^3.3.3
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-svelte: ^3.2.7
  react: ^18.3.1
  react-dom: ^18.3.1
  sharp: ^0.33.5
  svelte: ^4.2.19
  svelte-check: ^4.0.5
  svelte-preprocess: ^6.0.3
  tailwindcss: ^3.4.3
  typescript: ^5.6.3
  vite: ^5.4.11
  vitest: ^2.1.4
  vue: ^3.5.12
  zod: ^3.23.8
