packages:
  - apps/*
  - apps-svelte/*
  - packages/*
  - packages/ui-components/*
  - packages/utils/*
  - '!**/test/**'
  - '!**/.vercel/**'
  - '!**/cache-directory/**'
  - '!**/dist/**'
  - '!**/build/**'
  - '!**/.turbo/**'

catalog:
  '@astrojs/check': ^0.9.4
  '@astrojs/markdoc': ^0.15.0
  '@astrojs/mdx': ^4.3.0
  '@astrojs/node': ^9.2.2
  '@astrojs/preact': ^4.1.0
  '@astrojs/react': ^4.3.0
  '@astrojs/rss': ^4.0.12
  '@astrojs/sitemap': ^3.4.1
  '@astrojs/solid-js': ^5.1.0
  '@astrojs/starlight': ^0.34.3
  '@astrojs/starlight-markdoc': ^0.4.0
  '@astrojs/vercel': ^8.2.1
  '@astrojs/vue': ^5.1.0
  '@custom-elements-manifest/analyzer': 0.10.4
  '@eslint/compat': ^1.3.1
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.31.0
  '@eslint/json': ^0.13.0
  '@eslint/markdown': ^7.0.0
  '@headlessui/react': ^2.2.4
  '@headlessui/vue': ^1.7.23
  '@heroicons/react': ^2.2.0
  '@heroicons/vue': ^2.2.0
  '@iarna/toml': ^2.2.5
  '@iconify-json/mdi': ^1.2.3
  '@next/eslint-plugin-next': ^15.3.5
  '@open-wc/testing': ^4.0.0
  '@playform/compress': ^0.2.0
  '@preact/preset-vite': ^2.10.2
  '@preact/signals': ^2.2.1
  '@prettier/plugin-oxc': ^0.0.4
  '@sentry/astro': ^8.55.0
  '@sentry/browser': ^8.55.0
  '@sentry/cli': ^2.46.0
  '@sentry/vite-plugin': ^3.5.0
  '@tailwindcss/cli': ^4.1.11
  '@tailwindcss/forms': ^0.5.10
  '@tailwindcss/postcss': ^4.1.11
  '@tailwindcss/typography': ^0.5.16
  '@tailwindcss/vite': ^4.1.11
  '@types/canvas-confetti': ^1.9.0
  '@types/node': ^22.16.3
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@typescript-eslint/parser': ^8.36.0
  '@vitejs/plugin-react': ^4.6.0
  '@vitejs/plugin-vue': ^6.0.0
  '@vitest/browser': ^3.2.4
  '@webcomponents/template-shadowroot': ^0.2.1
  add: ^2.0.6
  astro: ^5.11.0
  astro-embed: ^0.9.0
  astro-eslint-parser: ^1.2.2
  astro-icon: ^1.1.5
  astro-og-canvas: ^0.7.0
  autoprefixer: ^10.4.21
  canvas-confetti: ^1.9.3
  clsx: ^2.1.1
  cssnano: ^7.0.7
  daisyui: ^5.0.46
  date-fns: ^4.1.0
  dotenv: ^17.2.0
  eslint: ^9.31.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-astro: ^1.3.1
  eslint-plugin-barrel-files: ^3.0.1
  eslint-plugin-lit: ^2.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-regexp: ^2.9.0
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-solid: ^0.14.5
  eslint-plugin-svelte: ^3.10.1
  eslint-plugin-turbo: ^2.5.4
  eslint-plugin-vue: ^10.3.0
  eslint-plugin-wc: ^3.0.1
  globals: ^16.3.0
  jest: ^30.0.4
  lit: ^3.3.1
  lorem-ipsum: ^2.0.8
  luxon: ^3.6.1
  open-props: ^1.7.15
  playwright: ^1.54.1
  postcss: ^8.5.6
  postcss-custom-media: ^11.0.6
  postcss-html: ^1.8.0
  postcss-import: ^16.1.1
  postcss-jit-props: ^1.0.16
  postcss-nesting: ^13.0.2
  postcss-pow: ^1.0.1
  preact: ^10.26.9
  prettier: ^3.6.2
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-tailwindcss: ^0.6.14
  prettier-plugin-toml: ^2.0.6
  prettier-plugin-vue: ^1.1.6
  react: ^19.1.0
  react-dom: ^19.1.0
  rollup-plugin-visualizer: ^6.0.3
  sharp: ^0.34.3
  solid-js: ^1.9.7
  svelte-eslint-parser: ^1.2.0
  tailwind-merge: ^3.3.1
  tailwindcss: 4.1.11
  theme-change: ^2.5.0
  tsup: ^8.5.0
  typescript: ^5.8.3
  typescript-eslint: ^8.36.0
  vite: ^6.3.5
  vitest: ^3.2.4
  vue: ^3.5.17
  vue-eslint-parser: ^10.2.0
  zod: ^3.24.2
  zod-validation-error: ^3.5.3

catalogs:
  svelte5:
    '@astrojs/svelte': ^7.1.0
    '@sveltejs/adapter-auto': ^6.0.1
    '@sveltejs/adapter-vercel': ^5.7.2
    '@sveltejs/kit': ^2.22.5
    '@sveltejs/vite-plugin-svelte': ^6.0.0
    '@testing-library/jest-dom': ^6.6.3
    '@testing-library/svelte': ^5.2.8
    prettier-plugin-svelte: ^3.4.0
    svelte: ^5.35.6
    svelte-check: ^4.2.2
    svelte-preprocess: ^6.0.3
    vitest-browser-svelte: ^1.0.0
