packages:
  - apps/*
  - apps-svelte/*
  - packages/*
  - packages/ui-components/*
  - "!**/test/**"
  - "!**/.vercel/**"
  - "!**/cache-directory/**"
catalog:
  "@astrojs/check": ^0.9.4
  "@astrojs/preact": ^4.0.0
  "@preact/signals": ^1.3.1
  "@astrojs/react": ^4.0.0
  "@astrojs/mdx": ^4.0.1
  "@astrojs/rss": ^4.0.10
  "@astrojs/sitemap": ^3.2.1
  "@astrojs/svelte": ^7.0.1
  "@astrojs/tailwind": ^5.1.3
  "@astrojs/vercel": ^8.0.0
  "@astrojs/vue": ^5.0.1
  "@custom-elements-manifest/analyzer": ^0.10.3
  "@eslint/compat": ^1.2.4
  "@iconify-json/mdi": ^1.2.1
  "@open-wc/testing": ^4.0.0
  "@shoelace-style/shoelace": ^2.17.1
  "@types/react": ^19.0.1
  "@types/react-dom": ^18.3.2
  "@vanilla-extract/vite-plugin": ^4.0.16
  "@web/test-runner": ^0.19.0
  "@webcomponents/template-shadowroot": ^0.2.1
  add: ^2.0.6
  astro: ^5.0.3
  astro-icon: ^1.1.4
  autoprefixer: ^10.4.20
  cssnano: ^7.0.6
  dotenv: ^16.4.7
  eslint: ^9.16.0
  jest: ^29.7.0
  lit: ^3.2.1
  open-props: ^1.7.7
  postcss: ^8.4.49
  postcss-custom-media: ^11.0.5
  postcss-html: ^1.7.0
  postcss-import: ^16.1.0
  postcss-jit-props: ^1.0.14
  postcss-nesting: ^13.0.1
  postcss-pow: ^1.0.1
  preact: ^10.25.1
  prettier: ^3.4.2
  prettier-plugin-astro: ^0.14.1
  react: ^18.3.1
  react-dom: ^18.3.1
  sharp: ^0.33.5
  svelte: ^4.2.19
  svelte-check: ^4.0.7
  svelte-preprocess: ^6.0.3
  tailwindcss: ^3.4.3
  typescript: ^5.7.2
  vite: ^5.4.11
  vitest: ^2.1.6
  vue: ^3.5.13
  zod: ^3.23.8
catalogs:
  astro4:
    "@astrojs/check": ^0.9.4
    "@astrojs/starlight": ^0.29.0
    "@astrojs/vercel": ^7.8.2
    "@astrojs/lit": ^4.3.0
    astro: ^4.16.14
    sharp: ^0.33.5
  svelte5:
    "@astrojs/svelte": ^7.0.1
    "@sveltejs/adapter-auto": ^3.3.1
    svelte: ^5.8.1
    svelte-check: ^4.1.1
    prettier-plugin-svelte: ^3.3.2
    vite: ^6.0.3
