[[users]]
id = 1
name = "John Doe"
email = "john.doe@example.com"
role = "Admin"
status = "active"
lastLogin = "2024-01-15"
avatar = "https://picsum.photos/40/40?random=1"
joinDate = "2023-03-15"
department = "Engineering"
location = "San Francisco, CA"

[[users]]
id = 2
name = "Jane Smith"
email = "jane.smith@example.com"
role = "Editor"
status = "active"
lastLogin = "2024-01-14"
avatar = "https://picsum.photos/40/40?random=2"
joinDate = "2023-05-22"
department = "Marketing"
location = "New York, NY"

[[users]]
id = 3
name = "Bob Johnson"
email = "bob.johnson@example.com"
role = "Viewer"
status = "inactive"
lastLogin = "2024-01-10"
avatar = "https://picsum.photos/40/40?random=3"
joinDate = "2023-01-08"
department = "Sales"
location = "Chicago, IL"

[[users]]
id = 4
name = "Alice Brown"
email = "alice.brown@example.com"
role = "Editor"
status = "pending"
lastLogin = "2024-01-12"
avatar = "https://picsum.photos/40/40?random=4"
joinDate = "2023-11-30"
department = "Design"
location = "Austin, TX"

[[users]]
id = 5
name = "Charlie Wilson"
email = "charlie.wilson@example.com"
role = "Admin"
status = "active"
lastLogin = "2024-01-16"
avatar = "https://picsum.photos/40/40?random=5"
joinDate = "2022-09-12"
department = "Engineering"
location = "Seattle, WA"

[[users]]
id = 6
name = "Diana Martinez"
email = "diana.martinez@example.com"
role = "Manager"
status = "active"
lastLogin = "2024-01-15"
avatar = "https://picsum.photos/40/40?random=6"
joinDate = "2022-07-04"
department = "Operations"
location = "Los Angeles, CA"

[[users]]
id = 7
name = "Erik Thompson"
email = "erik.thompson@example.com"
role = "Developer"
status = "active"
lastLogin = "2024-01-13"
avatar = "https://picsum.photos/40/40?random=7"
joinDate = "2023-08-18"
department = "Engineering"
location = "Portland, OR"

[[users]]
id = 8
name = "Fiona Davis"
email = "fiona.davis@example.com"
role = "Designer"
status = "inactive"
lastLogin = "2024-01-05"
avatar = "https://picsum.photos/40/40?random=8"
joinDate = "2023-06-10"
department = "Design"
location = "Miami, FL"

[[users]]
id = 9
name = "George Miller"
email = "george.miller@example.com"
role = "Analyst"
status = "pending"
lastLogin = "2024-01-11"
avatar = "https://picsum.photos/40/40?random=9"
joinDate = "2023-12-01"
department = "Data"
location = "Boston, MA"

[[users]]
id = 10
name = "Hannah Lee"
email = "hannah.lee@example.com"
role = "Manager"
status = "active"
lastLogin = "2024-01-16"
avatar = "https://picsum.photos/40/40?random=10"
joinDate = "2022-04-20"
department = "Marketing"
location = "Denver, CO"

# Products section
[[products]]
id = "PROD-001"
name = "Wireless Headphones"
category = "Electronics"
price = 149.99
stock = 25
rating = 4.5
featured = true
description = "High-quality wireless headphones with noise cancellation"
brand = "SoundMax"
sku = "SM-WH-001"

[[products]]
id = "PROD-002"
name = "Coffee Mug"
category = "Kitchen"
price = 12.99
stock = 100
rating = 4.2
featured = false
description = "Ceramic coffee mug with ergonomic handle"
brand = "HomeEssentials"
sku = "HE-CM-002"

[[products]]
id = "PROD-003"
name = "Laptop Stand"
category = "Office"
price = 89.99
stock = 15
rating = 4.8
featured = true
description = "Adjustable aluminum laptop stand for better ergonomics"
brand = "DeskPro"
sku = "DP-LS-003"

[[products]]
id = "PROD-004"
name = "Water Bottle"
category = "Sports"
price = 24.99
stock = 50
rating = 4.0
featured = false
description = "Stainless steel insulated water bottle"
brand = "HydroLife"
sku = "HL-WB-004"

[[products]]
id = "PROD-005"
name = "Bluetooth Speaker"
category = "Electronics"
price = 79.99
stock = 8
rating = 4.6
featured = true
description = "Portable Bluetooth speaker with 12-hour battery life"
brand = "SoundMax"
sku = "SM-BS-005"

[[products]]
id = "PROD-006"
name = "Desk Lamp"
category = "Office"
price = 45.99
stock = 30
rating = 4.3
featured = false
description = "LED desk lamp with adjustable brightness"
brand = "LightCorp"
sku = "LC-DL-006"

[[products]]
id = "PROD-007"
name = "Smartphone Case"
category = "Electronics"
price = 19.99
stock = 75
rating = 4.1
featured = false
description = "Protective silicone smartphone case"
brand = "GuardTech"
sku = "GT-SC-007"

[[products]]
id = "PROD-008"
name = "Yoga Mat"
category = "Sports"
price = 34.99
stock = 40
rating = 4.7
featured = true
description = "Non-slip yoga mat with alignment guides"
brand = "FlexFit"
sku = "FF-YM-008"
